---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: wp.test.heb-commerce-platform.com
    http:
      paths:
        - path: /
          backend:
            serviceName: wordpress
            servicePort: 80
  tls:
  - hosts:
    - wp.test.heb-commerce-platform.com
    secretName: wordpress-tls
