google:
  project: heb-sadc-training
  region: us-central1
terraform:
  prefix: test
cluster:
  name: test
  network: default
  subnetwork: default
  zone: us-central1-b
  # additional_zones:
  #   - us-central1-c
  #   - us-central1-f
  min_master_version: 1.11.3-gke.18
  machine_type: n1-standard-4
  min_node_count: 1
  max_node_count: 5
dnsZone:
  name: test-heb-commerce-platform
  dns_name: test.heb-commerce-platform.com
