version: '3'
services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    environment:
      ANSIBLE_REMOTE_USER: ${USER}
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
