version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      STATSD_HOST: localhost
      STATSD_PREFIX: example.
      DATADOG_ENV: local
    ports:
      - "3000:3000"
